version: '2'
services:
  test:
    extends:
      file: docker-compose-base.yml
      service: base
    entrypoint: python manage.py test -v2
    env_file:
        - conf/test.env
  sut:
    image: ubuntu
    command: "true"
